<?php

// This module scores the library hours node as it is entered.
function score_locations_node_view($node, $view_mode, $langcode)
{
	//kpr($node);
}

function score_locations_form_library_hours_node_form_alter(&$form, &$form_state, $form_id)
{
	//Disable Access to Score field for everyone except the Admin

	// Change Text of Add another item
}

function score_locations_node_submit($node)
{
	// Get All Start Days
	dpm(get_all_start_dates($node));
	
	// Get All End Days
	dpm(get_all_end_dates($node));

	// Get Days in Chosen Range
	$days_in_chosen_range = get_days_chosen_range_in_each_fieldset();
	//**********************************************************************************************
	//die(kpr($node->field_time_field_collection['und']));
	// Get all days of week from the taxonomy
	//dpm(get_all_days_of_week());
	//dpm($node->field_time_field_collection['und']['0']['field_start_date']['und']['0']['value']);
	//dpm($node->field_time_field_collection['und']['0']['field_start_date']);
	//dpm(get_all_start_dates());
	
	//user entered Start and end date
	// All Start Dates

	// All End Dates
	//***********************************************************************************************

}

function get_all_days_of_week()
{
	// Days of Week Taxonomy
	$days_of_week = array();
	// Load Days of week taxonomy
	$days_of_week_taxonomy = taxonomy_term_load_multiple(array(),array('vid' => 4));
	foreach($days_of_week_taxonomy as $day)
	{
		// Load days of week from the taxonomy into the array of days
		$days_of_week[] = $day->name;
	}
	return $days_of_week;
}


function get_all_start_dates($node)
{
	
	$start_dates = array();
	
	// For all Fieldsets
	for($i = 0; $i <20; $i++)
	{
		if(isset($node->field_time_field_collection['und'][$i]))
		{
			for($j=0; $j<sizeof($node->field_time_field_collection['und'][$i]['field_start_date']['und']); $j++)
			{
				$start_dates[] = $node->field_time_field_collection['und'][$i]['field_start_date']['und'][$j]['value'];
			}
		}
	}
	return $start_dates;
}

function get_all_end_dates($node)
{
	
	$end_dates = array();
	
	// For all Fieldsets
	for($i = 0; $i <20; $i++)
	{
		if(isset($node->field_time_field_collection['und'][$i]))
		{
			for($j=0; $j<sizeof($node->field_time_field_collection['und'][$i]['field_end_date']['und']); $j++)
			{
				$end_dates[] = $node->field_time_field_collection['und'][$i]['field_end_date']['und'][$j]['value'];
			}
		}
	}
	return $end_dates;
}

function get_days_chosen_range_in_each_fieldset()
{
	//Get range
	for($i = 0; $i <20; $i++)
	{
		if(isset($node->field_time_field_collection['und'][$i]))
		{
			

		}
	}

}


